### PR TITLE
Tooltips created

### PR DESCRIPTION
**Pull request by annouri**

### CODE REVIEW

**Comment by annouri** [comment]
@e-hamza I created Tooltips component. Could you please review my code?

**Review by e-hamza — APPROVED** [review]
Thanks @annouri, I just checked and it looks great!
We can shorten the code a little in the future but for now it's great.

**Comment by e-hamza** [comment]
Hey @annouri, I'll approve/merge this but we normally merge feature branches to `dev`, not straight to `main`. Hopefully no conflicts will arise!

**Comment by annouri** [comment]
Hey  @e-hamza 😄, I will work on shortening the code for future components and ensure the pull request is made to the dev branch 😉, I appreciate your feedback boss 😎

**Pull request merged**
